### PR TITLE
Biased data splitter

### PR DESCRIPTION
**Pull request by weitaiting**
- Biased data partitioner create a DataLoader but with only the certain classes specified
- Wraps `datasets.MNIST` in reality
- Please run the unit test to see if it works

### CODE REVIEW

**Comment by michlimlim** [comment]
Okay, will write some unit tests

**Comment by weitaiting** [comment]
> Okay, will write some unit tests

There are unit tests already

**Comment by michlimlim** [comment]
What do you mean by "Please run the unit test to see if it works"

**Comment by weitaiting** [comment]
> What do you mean by "Please run the unit test to see if it works"

I meant "it works, you can double check by running the unit tests"

**Comment by michlimlim** [comment]
Gotcha! Yes it works! thanks!

**Pull request merged**
